apiVersion: v1
kind: Secret
metadata:
  name: rathena-openkore-pwd
  labels:
    app: rathena
type: Opaque
data:
  user-pwd: cDRzc0B3MHJk # p4ss@w0rd in base64
  mysql-pwd: cDRzc0B3MHJk # p4ss@w0rd in base64
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2, before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: rathena-openkore
  labels:
    app: rathena
spec:
  replicas: 20
  selector:
    matchLabels:
      app: rathena
      component: openkore
      version: v1.0
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rathena
        component: openkore
        version: v1.0
    spec:
      containers:
      - image: cmilanf/openkore:latest
        imagePullPolicy: Always
        name: rathena-openkore
        env:
        - name: OK_PWD
          valueFrom:
            secretKeyRef:
              name: rathena-openkore-pwd
              key: user-pwd
        - name: MYSQL_PWD
          valueFrom:
            secretKeyRef:
              name: rathena-openkore-pwd
              key: mysql-pwd
        - name: MYSQL_HOST
          value: "10.0.0.2"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_DB
          value: "rathena"
        - name: OK_IP
          value: "10.0.0.3"
        - name: OK_USERNAME
          value: "botijo"
        - name: OK_CHAR
          value: "1"
        - name: OK_USERNAMEMAXSUFFIX
          value: "5000"
        - name: OK_KILLSTEAL
          value: "1"
        - name: TERM
          value: "xterm-color"
